spring:
  config:
    import: application-oauth.yml
  boot:
    devtools:
      remote:
        debug: true
  session:
    store-type: redis
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  sql:
    init:
      mode: ${SQL_INIT_MODE}
logging.level:
  cos.peerna: ${LOG_LEVEL}
  org:
    hibernate:
      SQL: info
      orm.jdbc.bind: trace
    springframework:
      security: ${LOG_LEVEL}
      data:
        redis:
          core:
            RedisTemplate: debug

server:
  error:
    include-stacktrace: on_param
    include-message: always
openai:
  token: ${GPT_TOKEN}
